#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\RazorHelpers\NotyBuilder.cshtml"
    using Common.Controller.NotyHelper;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class NotyBuilder
    {

public static System.Web.WebPages.HelperResult ShowNotyMessages(Noty notyInput)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\RazorHelpers\NotyBuilder.cshtml"
 
    if (notyInput == null)
    {
        return;
    }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <script>\r\n    $(function() {\r\n\r\n");



#line 18 "..\..\RazorHelpers\NotyBuilder.cshtml"
         foreach (var message in notyInput.NotyMessages)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "var  overrideOptions= {};\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " overrideOptions.layout= \'");



#line 21 "..\..\RazorHelpers\NotyBuilder.cshtml"
 WebViewPage.WriteTo(@__razor_helper_writer, message.Location);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.type= \'");



#line 22 "..\..\RazorHelpers\NotyBuilder.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, message.Type);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.text=\'");



#line 23 "..\..\RazorHelpers\NotyBuilder.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, message.Message);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "var overrideAnimation={};\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideAnimation.open= \'animated ");



#line 25 "..\..\RazorHelpers\NotyBuilder.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, message.OpenAnimation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " overrideAnimation.close= \'animated ");



#line 26 "..\..\RazorHelpers\NotyBuilder.cshtml"
           WebViewPage.WriteTo(@__razor_helper_writer, message.CloseAnimation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\';\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.maxVisible= ");



#line 27 "..\..\RazorHelpers\NotyBuilder.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, notyInput.MaxVisibleForQueue);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ";\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.closeWith= [\'");



#line 28 "..\..\RazorHelpers\NotyBuilder.cshtml"
    WebViewPage.WriteTo(@__razor_helper_writer, message.CloseWith);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\'];\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.buttons= false;\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideAnimation.speed= ");



#line 30 "..\..\RazorHelpers\NotyBuilder.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, message.AnimateSpeed);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ";\r\n");



#line 31 "..\..\RazorHelpers\NotyBuilder.cshtml"

             if (message.IsSwing)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " overrideAnimation.easing=\'swing\';\r\n");



#line 35 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                             }

                if (notyInput.DismissQueue)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " overrideOptions.dismissQueue= true;\r\n");



#line 40 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                            }
                if (message.IsForce)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.force= true;\r\n");



#line 44 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                           }
                if (message.IsKiller)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions. killer= true;\r\n");



#line 48 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                                     }
                if (message.IsModal)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.modal=true;\r\n");



#line 52 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                            }
                if (message.IsSticky)
                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.timeout= false;\r\n");



#line 56 "..\..\RazorHelpers\NotyBuilder.cshtml"

                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                 ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideAnimation.fadeSpeed=50;\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                 ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "overrideOptions.animation=overrideAnimation;\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                 ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "noty(overrideOptions);\r\n");



#line 61 "..\..\RazorHelpers\NotyBuilder.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    });\r\n\r\n    </script>\r\n");



#line 66 "..\..\RazorHelpers\NotyBuilder.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
