#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ViewModel;
    using Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/ManageLogins.cshtml")]
    public partial class _Views_Manage_ManageLogins_cshtml : System.Web.Mvc.WebViewPage<ViewModel.Account.ManageLoginsViewModel>
    {
        public _Views_Manage_ManageLogins_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Manage\ManageLogins.cshtml"
  
    ViewBag.Title = "Manage your external logins";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Manage\ManageLogins.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n\r\n<p");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Manage\ManageLogins.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 9 "..\..\Views\Manage\ManageLogins.cshtml"
 if (Model.CurrentLogins.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <h4>Registered Logins</h4>\r\n");

WriteLiteral("    <table");

WriteLiteral(" class=\"table table-striped table-hover table-bordered table-condensed\"");

WriteLiteral(">\r\n        <tbody>\r\n");

            
            #line 14 "..\..\Views\Manage\ManageLogins.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Manage\ManageLogins.cshtml"
             foreach (var account in Model.CurrentLogins)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 17 "..\..\Views\Manage\ManageLogins.cshtml"
                   Write(account.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>\r\n");

            
            #line 19 "..\..\Views\Manage\ManageLogins.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Manage\ManageLogins.cshtml"
                         if (ViewBag.ShowRemoveButton)
                        {
                            using (Html.BeginForm("RemoveLogin", "Manage"))
                            {
                                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Manage\ManageLogins.cshtml"
                           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Manage\ManageLogins.cshtml"
                                                        

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n");

WriteLiteral("                                    ");

            
            #line 25 "..\..\Views\Manage\ManageLogins.cshtml"
                               Write(Html.Hidden("loginProvider", account.LoginProvider));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 26 "..\..\Views\Manage\ManageLogins.cshtml"
                               Write(Html.Hidden("providerKey", account.ProviderKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Remove\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1106), Tuple.Create("\"", 1172)
, Tuple.Create(Tuple.Create("", 1114), Tuple.Create("Remove", 1114), true)
, Tuple.Create(Tuple.Create(" ", 1120), Tuple.Create("this", 1121), true)
            
            #line 27 "..\..\Views\Manage\ManageLogins.cshtml"
                                  , Tuple.Create(Tuple.Create(" ", 1125), Tuple.Create<System.Object, System.Int32>(account.LoginProvider
            
            #line default
            #line hidden
, 1126), false)
, Tuple.Create(Tuple.Create(" ", 1148), Tuple.Create("login", 1149), true)
, Tuple.Create(Tuple.Create(" ", 1154), Tuple.Create("from", 1155), true)
, Tuple.Create(Tuple.Create(" ", 1159), Tuple.Create("your", 1160), true)
, Tuple.Create(Tuple.Create(" ", 1164), Tuple.Create("account", 1165), true)
);

WriteLiteral(" />\r\n                                </div>\r\n");

            
            #line 29 "..\..\Views\Manage\ManageLogins.cshtml"
                            }
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral(" &nbsp;\r\n");

            
            #line 34 "..\..\Views\Manage\ManageLogins.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 37 "..\..\Views\Manage\ManageLogins.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

            
            #line 40 "..\..\Views\Manage\ManageLogins.cshtml"
}

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Manage\ManageLogins.cshtml"
 if (Model.OtherLogins.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <h4>Add another service to log in.</h4>\r\n");

WriteLiteral("    <hr />\r\n");

            
            #line 45 "..\..\Views\Manage\ManageLogins.cshtml"
    using (Html.BeginForm("LinkLogin", "Manage"))
    {
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Manage\ManageLogins.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Manage\ManageLogins.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <p>\r\n");

            
            #line 50 "..\..\Views\Manage\ManageLogins.cshtml"
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Manage\ManageLogins.cshtml"
             foreach (var p in Model.OtherLogins)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1862), Tuple.Create("\"", 1888)
            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
, Tuple.Create(Tuple.Create("", 1867), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1867), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1905), Tuple.Create("\"", 1934)
            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
                                , Tuple.Create(Tuple.Create("", 1913), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1913), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1935), Tuple.Create("\"", 1979)
, Tuple.Create(Tuple.Create("", 1943), Tuple.Create("Log", 1943), true)
, Tuple.Create(Tuple.Create(" ", 1946), Tuple.Create("in", 1947), true)
, Tuple.Create(Tuple.Create(" ", 1949), Tuple.Create("using", 1950), true)
, Tuple.Create(Tuple.Create(" ", 1955), Tuple.Create("your", 1956), true)
            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                               , Tuple.Create(Tuple.Create(" ", 1960), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 1961), false)
, Tuple.Create(Tuple.Create(" ", 1971), Tuple.Create("account", 1972), true)
);

WriteLiteral(">");

            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                                                                                                                               Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 53 "..\..\Views\Manage\ManageLogins.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n        </div>\r\n");

            
            #line 56 "..\..\Views\Manage\ManageLogins.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
